# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (everyday)
  schedule: [{cron: "0 4 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # 设置服务器时区为东八区 
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
        
      - name: metrics
        uses: lowlighter/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: icy-blue
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          # plugin_achievements: yes
          # plugin_achievements_threshold: B      # Display achievements with rank X or higher
          # plugin_achievements_secrets: yes      # Display unlocked secrets achievements
          # plugin_achievements_display: detailed # Use detailed display
          # plugin_achievements_limit: 0          # Display all unlocked achievements (no limit)
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: issue,pr,ref/create,release,review,wiki,fork
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_licenses: yes
          plugin_licenses_setup: npm ci       # Command to setup target repository
          plugin_licenses_ratio: yes          # Display used licenses ratio
          plugin_licenses_legal: yes          # Display permissions, limitations and conditions
          plugin_lines: yes
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_people: yes
          plugin_people_limit: 100
          plugin_contributors: yes
          plugin_contributors_contributions: yes
